name: Build and Run Nginx

on:
  push:
    branches: [ "main" ]

jobs:
  test-nginx:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build Docker image
        run: |
          docker build -t mynginx .

      - name: Run Docker container
        run: |
          docker run -d -p 8080:80 --name test-nginx mynginx

      - name: Wait for container to start
        run: sleep 5

      - name: Test nginx response
        run: curl -I http://localhost:8080
